### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by magrathj** [francisco-ltech/virgil-apptpl#2]
Config file to use variables, needs to be updatable by virigil as currently its hard coded and when i tried to set a different path everything failed for me

**Comment by francisco-ltech** [comment]
They should be updated once deployed, right? Once you have the path entered by the user. We could "templatise" it here so we do search&replace on Virgil-cli.

**Comment by francisco-ltech** [comment]
@magrathj see if we can use this: https://github.com/cookiecutter/cookiecutter
